- name: install apache2 server
  apt:
     name: apache2
     state: present

  notify:
    - start apache2

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone project Repo
  git:
    repo: https://github.com/f1amy/laravel-realworld-example-app.git
    dest: /var/www/shoplikeaboss247
    clone: yes
    update: yes
    force: yes

- name: Updating web.php file
  ansible.builtin.copy:
    src: /home/vagrant/exam/files/web.php
    dest: /var/www/shoplikeaboss247/routes/web.php
    remote_src: no
    
- name: Setting permissions - 1
  shell: sudo chown -R www-data:www-data /var/www/shoplikeaboss247

- name: Setting permissions - 2
  shell: sudo chmod -R 775 /var/www/shoplikeaboss247

- name: Setting permissions - 3
  shell: sudo chmod -R 755 /var/www/shoplikeaboss247/storage

- name: Setting permissions - 4
  shell: sudo chgrp -R www-data /var/www/shoplikeaboss247/storage /var/www/shoplikeaboss247/bootstrap/cache


- name: Setting permissions - 5
  shell: sudo chmod -R ug+rwx /var/www/shoplikeaboss247/storage /var/www/shoplikeaboss247/bootstrap/cache

- name: Setting up Configuration File
  shell: sudo touch /etc/apache2/sites-available/shoplikeaboss247.conf

- name: Copy Configuration file
  ansible.builtin.copy:
    src: /home/vagrant/exam/files/shoplikeaboss247.conf
    dest: /etc/apache2/sites-available/shoplikeaboss247.conf
    remote_src: no

- name: Setting up .env File
  shell: sudo touch /var/www/shoplikeaboss247/.env


- name: Copy .env file
  ansible.builtin.copy:
    src: /home/vagrant/exam/files/.env
    dest: /var/www/shoplikeaboss247/.env
    remote_src: no

- name: Enable Apache 2 Mod Rewrite
  shell: sudo a2enmod rewrite

  notify:
    - restart apache2


- name: Creating File
  shell: sudo touch /var/www/shoplikeaboss247/.htaccess

- name: Copy htaccess file
  ansible.builtin.copy:
    src: /home/vagrant/exam/files/.htaccess
    dest: /var/www/shoplikeaboss247/.htaccess
    remote_src: no



- name: Disabling default Configuration
  shell: cd /var/www/shoplikeaboss247/ && sudo a2dissite 000-default && cd

- name: Enabling new Configuration
  shell: cd /var/www/shoplikeaboss247/ && sudo a2ensite shoplikeaboss247.conf && cd

  notify:
    - restart apache2
