- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: setup

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php


- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: mysql

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: apache_config

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: ssl
