- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Installing php dependencies
  ansible.builtin.apt:
    pkg:
    - lsb-release
    - apt-transport-https
    - ca-certificates

- name: Get php URL
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /root/etc/apt/trusted.gpg.d/php.gpg

- name: Still installing PHP
  shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
  
  
- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Install PHP and dependencies
  ansible.builtin.apt:
    pkg:
    - php
    - libapache2-mod-php
    - php8.1-mysql
    - php8.1-common
    - php8.1-mysql
    - php8.1-xml
    - php8.1-xml
    - php8.1-curl
    - php8.1-gd
    - php8.1-imagick
    - php8.1-cli
    - php8.1-dev
    - php8.1-imap
    - php8.1-mbstring
    - php8.1-opcache
    - php8.1-soap
    - php8.1-zip
    - php8.1-intl
    state: present


- name: Download php-composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: create composer file 
  shell: sudo touch /usr/local/bin/composer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: make composer executable
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file
